# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateField()),
                ('last_used', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_bucket', models.CharField(max_length=30)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_complete', models.BooleanField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.Group')),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstanding_payment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.Receipt')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('venmo_handle', models.CharField(max_length=30)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('role', models.CharField(max_length=30)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(related_name='people', through='chop.UserMembership', to='chop.Group'),
        ),
        migrations.AddField(
            model_name='user',
            name='receipts',
            field=models.ManyToManyField(related_name='receiptmany', through='chop.ReceiptMembership', to='chop.Receipt'),
        ),
        migrations.AddField(
            model_name='receiptmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.User'),
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.Receipt'),
        ),
        migrations.AddField(
            model_name='item',
            name='user_owns',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chop.User'),
        ),
    ]
