# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0002_remove_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='last_used',
            field=models.DateField(auto_now_add=True),
        ),
    ]
