# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0003_remove_users_venmo_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='venmo',
            field=models.CharField(default='hello', max_length=30),
        ),
    ]
