# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0007_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='+1', max_length=30),
        ),
    ]
