# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0008_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmembership',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
