# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 04:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0009_receiptmembership_notified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chop.Group'),
        ),
    ]
