# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chop', '0012_remove_item_user_owns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='group',
        ),
        migrations.AddField(
            model_name='receipt',
            name='group',
            field=models.ManyToManyField(to='chop.Group'),
        ),
    ]
